modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="decrafter"
version="1.1"
displayName="Decrafter"
displayURL="https://jland.dev"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="fiwnq"
description="Adds a decrafter block to easily convert items and blocks into their respective items used to craft it."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.decrafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration