modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="decrafter"
version="1.0"
displayName="Decrafter"
displayURL="https://twitter.com/fiwnq"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="fiwnq"
description="Adds a recycler block to easily convert items and blocks into their respective items used to craft it."

[[dependencies.decrafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"
